MSCSE-5: add db and refactor structure of project
sava-cska/SPbSU-Calculator pull request #9
Opened 2022-09-11 15:23 UTC by ainurbl

2022-09-11 20:04 UTC, sava-cska requested changes

2022-09-11 20:04 UTC, sava-cska commented on server/internal/utils/utils.go
> +}
Чем различается ParseBody и ParseJSON?

2022-09-11 21:20 UTC, mbnexttime commented on server/internal/app/actions/evaluations/list_action.go
> +		logger.Debugf("GET - Called URI %s", request.RequestURI)
тут post

2022-09-12 06:53 UTC, sava-cska approved these changes

2022-09-12 07:10 UTC, merged